version: "3"
services:
  frontend:
    build: ./frontend
    volumes:                 
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
      - "80:80"
    environment:
      - NODE_ENV=development
    stdin_open: true
    depends_on: 
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
