version: "3"
services:
  frontend:
    build: ./frontend
    volumes:                 
      - ./frontend:/app/frontend
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
