version: "3"
services:
        frontend:
                container_name: react_app
                build:
                        context: ./psn-front
                        dockerfile: Dockerfile
                image: 
