version: "3"
services:
  db:
    image: postgres:10.4
    # restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./backend/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    stdin_open: true
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "35432:5432"
    

  frontend:
    build: 
      context: ./frontend
      dockerfile: ${DFILE}
    volumes:                 
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
      - "80:80"
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    stdin_open: true
    depends_on: 
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on: 
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${NODE_PORT}
      RANDOM: random
    links:
      - db:db

volumes:
  pgdata: